version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/backend_challenge_001
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
