# Generated by rspec-sinatra. (2017-01-19 13:16:27 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '../..', 'daycare/daycare.rb')

require 'rack/test'
require 'rspec'

module RSpecMixin
  include Rack::Test::Methods

  def app()
    Daycare
  end
end

RSpec.configure { |c| c.include RSpecMixin }

RSpec.configure do |config|

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

end
