development:
  sessions:
    default:
      database: dalia_backend_challenge_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: dalia_backend_challenge_test
      hosts:
        - localhost:27017
