production:
  adapter: postgresql
  database: robolandia
  username: robolandia
  password: robolandia
  encoding: utf8  
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: robolandia_tests
  username: robolandia
  password: robolandia
  encoding: utf8  
  host: localhost
  pool: 5