development:
  # Configure available database sessions (required)
  sessions:
    # Defines the default session (required)
    default:
      # Defines the name of the default database that Mongoid can connect to (required).
      database: daliarobots_development
      # Provides the hosts the default session can connect to. Must be an array of host:port pairs (required)
      hosts:
        - localhost:27017
  # Configure Mongoid specific options. (optional)
  options:
    # Raise an error when performing a #find and the document is not found (default: true)
    raise_not_found_error: false
test:
  sessions:
    default:
      database: daliarobots_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
